### ISSUE TITLE
Let's do not compensate sensors

### ISSUE THREAD

**Issue by jan-a-krzywda** [KREFT-QS-13/learning-QDs-parameters#4]
At some point we agreed to not compensate sensor, and work on more realistic CSDs. With the current setup, in terms of lambda and d, and without `compensate_sensors=True` the CSDs are the thing of beauty 

<img width="508" alt="image" src="https://github.com/user-attachments/assets/b1383549-4b19-4065-b5b0-87649b8b5003">

**Comment by KREFT-QS-13** [comment]
Done. Changed to **False** (commit 2775936).
