### ISSUE TITLE
Too small self-capacitance of the sensor dot. 

### ISSUE THREAD

**Issue by jan-a-krzywda** [KREFT-QS-13/learning-QDs-parameters#6]
1. This is on me... but I think that self-capacitance of sensor dot should be larger, as it is larger and has a lot of metal round that. Here I applied the quick-fix:
<img width="192" alt="image" src="https://github.com/user-attachments/assets/acdf3221-eabf-40a3-806b-3f7443f6433f">

where the factor of 5 comes from: C ~ r and also a lot of metal around the SD. 

Resulting CSD are not that bad:
![image](https://github.com/user-attachments/assets/0e3933f0-b357-47f3-9e78-090597451141)

**Comment by KREFT-QS-13** [comment]
Commits df26e58 and d791c75 were resolved by increasing the sensors' self-capacitance as suggested.
