### ISSUE TITLE
Modeling the screening

### ISSUE THREAD

**Issue by jan-a-krzywda** [KREFT-QS-13/learning-QDs-parameters#7]
In reality, there is another reason why only nearest-neighbour, C_DD should be relevant and it is screening, i.e. coupling to the dot through another one is difficult to achieve. 

There are two methods to achieve that in our model:
1. Introduce a different p_dd for dot-sensor, since we would like to keep mutual C between central dot to be 5-20%.
2. Bring the sensor even closer, which connected with x5 capacitance of the sensor dot gives desired effect (see below)

**Comment by jan-a-krzywda** [comment]
This is the final result from the combination of #3, #4 , #5 , with r = 1.5d, and realistic amplitudes of the noise fast = 30ueV, slow = 10ueV noise (even the units are good). Lambda = 1 to assure this 5-20% of C_dd[off_diagonal], C_sensor = x* C_sensor0
![image](https://github.com/user-attachments/assets/841f247a-70f9-445f-b94f-af0834114ae6)

**Comment by KREFT-QS-13** [comment]
All previous issues were resolved. The main branch now generates similar results:
Sensor 0:
![image](https://github.com/user-attachments/assets/2efad298-a84c-4827-aafd-91eacd7065b6)
Sensor 1:
![image](https://github.com/user-attachments/assets/a209fcec-2760-44c6-bdb2-56138a4dde75)

Device config:
![image](https://github.com/user-attachments/assets/be205493-b828-49aa-9322-519ba95701e0)
